# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/guides/configure-coderabbit
# Install: https://github.com/marketplace/coderabbitai

language: "en"  # Review language (set to "tr" for Turkish)

reviews:
  # Automatically start review on each PR
  auto_review:
    enabled: true
    # Skip draft PRs, only review ready ones
    drafts: false
    # Only review PRs targeting these branches
    base_branches:
      - "dev"
      - "main"
      - "master"

  # Review profile — assertive = detailed, chill = only important issues
  profile: "assertive"

  # Generate high-level summary
  high_level_summary: true
  # Add summary to PR description
  auto_title_placeholder: "[CodeRabbit]"

  # No poems please
  poem: false

  # Review scope
  request_changes_workflow: true
  collapse_walkthrough: false
  sequence_diagrams: true

  # Path filtreleri — bunları incelemesin
  path_filters:
    - "!artifacts/**"
    - "!docs/benchmarks/**"
    - "!**/*.png"
    - "!**/*.svg"
    - "!**/*.jpg"
    - "!**/*.ico"
    - "!**/package-lock.json"
    - "!**/yarn.lock"

  # Path-specific instructions
  path_instructions:
    - path: "src/bantz/brain/**"
      instructions: |
        This directory contains Bantz's brain layer (orchestrator, router, finalizer).
        - Thread-safety is critical: check usage of threading.Lock
        - All LLM calls should be wrapped in try/except
        - Be careful with changes in orchestrator_loop.py, it's production code
    - path: "src/bantz/data/**"
      instructions: |
        Data platform layer. SQLite-backed, WAL journal mode.
        - Check thread-safety (usage of self._lock)
        - Verify TTL and expires_at calculations
        - Fingerprint calculations should be deterministic (sort_keys=True)
    - path: "src/bantz/skills/**"
      instructions: |
        Tool/skill modules. Each skill returns a tool_schema.
        - Check Google API rate limit handling
        - Credentials/tokens should not be hardcoded
        - Each public function should have a docstring
    - path: "tests/**"
      instructions: |
        Test files. Using pytest + pytest-asyncio.
        - Mocks should be at the correct scope (function/class/module)
        - Async tests must be decorated with @pytest.mark.asyncio
        - Flag any flaky test risks
    - path: "config/**"
      instructions: |
        Configuration files. Must not contain sensitive data.
        - No secrets/tokens/passwords
        - Example files (.example) should be up to date

chat:
  auto_reply: true

# Learning — learn from reviewer feedback
knowledge_base:
  learnings:
    scope: "auto"       # Learn from 👍/👎 on PRs
  jira:
    project_keys: []    # Not using Jira currently
  linear:
    team_keys: []       # Not using Linear currently

# Tonalite
tone_instructions: |
  Review in English. Be concise and clear.
  Use "🚨 CRITICAL:" prefix for critical bug/security issues.
  Use "💡 SUGGESTION:" prefix for minor style suggestions.
  At the end of each review, provide "Overall Assessment: ✅/⚠️/❌".
