"""bantz onboard — guided first-time setup wizard (Issue #1223).

Walks the user through:
1. Environment check (Python, .env, directories)
2. Google OAuth setup
3. LLM backend configuration
4. vLLM / Ollama endpoint validation
5. Sample config generation

Usage::

    $ bantz onboard
    $ bantz onboard --non-interactive
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

__all__ = ["run_onboard"]


# ============================================================================
# Helpers
# ============================================================================

def _ask(prompt: str, default: str = "", choices: Optional[list] = None) -> str:
    """Ask user for input with optional default and choices."""
    if choices:
        opts = "/".join(choices)
        full = f"{prompt} [{opts}] ({default}): " if default else f"{prompt} [{opts}]: "
    elif default:
        full = f"{prompt} ({default}): "
    else:
        full = f"{prompt}: "
    answer = input(full).strip()
    if not answer:
        return default
    if choices and answer.lower() not in [c.lower() for c in choices]:
        print(f"  Invalid choice. Options: {', '.join(choices)}")
        return _ask(prompt, default, choices)
    return answer


def _print_step(n: int, total: int, title: str) -> None:
    print(f"\n{'─' * 40}")
    print(f"  Step {n}/{total}: {title}")
    print(f"{'─' * 40}")


# ============================================================================
# Steps
# ============================================================================

def _step_env_check() -> bool:
    """Verify Python version and required dirs."""
    _print_step(1, 5, "Environment Check")
    v = sys.version_info
    print(f"  Python {v.major}.{v.minor}.{v.micro}", end="")
    if v >= (3, 10):
        print(" ✓")
    else:
        print(" ✗ — 3.10+ required")
        return False

    dirs = [
        Path("artifacts/logs"),
        Path("artifacts/results"),
        Path("artifacts/tmp"),
        Path("config"),
    ]
    for d in dirs:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            print(f"  Created: {d}")
        else:
            print(f"  {d} ✓")
    return True


def _step_env_file(non_interactive: bool = False) -> bool:
    """Ensure .env exists with basic variables."""
    _print_step(2, 5, "Environment Configuration")

    env_path = Path(".env")
    example_path = Path("config/bantz-env.example")

    if env_path.exists():
        print("  .env already exists ✓")
        return True

    if not example_path.exists():
        print("  ⚠ config/bantz-env.example not found, creating minimal .env")
        _write_minimal_env(env_path, non_interactive)
        return True

    if non_interactive:
        shutil.copy2(example_path, env_path)
        print(f"  Copied {example_path} → .env")
        return True

    copy = _ask("  Copy bantz-env.example to .env?", "y", ["y", "n"])
    if copy.lower() == "y":
        shutil.copy2(example_path, env_path)
        print(f"  Copied ✓")
    else:
        _write_minimal_env(env_path, non_interactive)
    return True


def _write_minimal_env(env_path: Path, non_interactive: bool = False) -> None:
    lines = [
        "# Bantz environment — generated by `bantz onboard`\n",
        "BANTZ_LLM_BACKEND=ollama\n",
        "# BANTZ_VLLM_URL=http://localhost:8000\n",
        "# GOOGLE_APPLICATION_CREDENTIALS=\n",
        "BANTZ_LOG_LEVEL=INFO\n",
    ]
    env_path.write_text("".join(lines))
    print(f"  Created minimal .env")


def _step_google_oauth(non_interactive: bool = False) -> bool:
    """Check or trigger Google OAuth."""
    _print_step(3, 5, "Google OAuth")

    token_path = Path.home() / ".config" / "bantz" / "token.json"
    alt_path = Path("token.json")

    for p in (token_path, alt_path):
        if p.exists():
            try:
                data = json.loads(p.read_text())
                if data.get("refresh_token"):
                    print(f"  Token found at {p} ✓")
                    return True
                print(f"  Token at {p} missing refresh_token — re-auth needed")
            except (json.JSONDecodeError, OSError):
                print(f"  Corrupt token at {p}")

    if non_interactive:
        print("  ⚠ No valid token — run `bantz google auth` manually")
        return True

    run_auth = _ask("  No Google token found. Run `bantz google auth` now?", "y", ["y", "n"])
    if run_auth.lower() == "y":
        try:
            from bantz.google.cli import main as google_main
            google_main(["auth"])
        except Exception as exc:
            print(f"  OAuth failed: {exc}")
            print("  Run manually: bantz google auth")
    else:
        print("  Skipped — run later: bantz google auth")
    return True


def _step_llm_backend(non_interactive: bool = False) -> bool:
    """Configure LLM backend."""
    _print_step(4, 5, "LLM Backend Configuration")

    backend = os.getenv("BANTZ_LLM_BACKEND", "")
    if backend:
        print(f"  Current backend: {backend} ✓")
    else:
        if non_interactive:
            print("  ⚠ BANTZ_LLM_BACKEND not set — defaulting to ollama")
            return True
        backend = _ask("  Choose LLM backend", "ollama", ["ollama", "vllm", "gemini"])
        print(f"  Set BANTZ_LLM_BACKEND={backend} in your .env")

    # Verify endpoint
    url = os.getenv("BANTZ_VLLM_URL") or os.getenv("VLLM_URL")
    if url:
        print(f"  Endpoint: {url}")
        try:
            import urllib.request
            req = urllib.request.Request(f"{url.rstrip('/')}/health", method="GET")
            req.add_header("User-Agent", "bantz-onboard/1.0")
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    print("  Endpoint reachable ✓")
                else:
                    print(f"  Unexpected status: {resp.status}")
        except Exception as exc:
            print(f"  ⚠ Cannot reach {url}: {exc}")
    else:
        print("  No LLM URL set — model will run locally or via API key")
    return True


def _step_summary() -> None:
    """Print final summary."""
    _print_step(5, 5, "Setup Complete")
    print("  Your environment is configured!")
    print()
    print("  Next steps:")
    print("    1. Review .env and fill in any missing secrets")
    print("    2. Run `bantz doctor` to verify everything")
    print("    3. Start Bantz: `bantz --once 'What is on my calendar today?'`")
    print()


# ============================================================================
# Main entry
# ============================================================================

def run_onboard(*, non_interactive: bool = False) -> int:
    """Run the onboarding wizard.

    Returns exit code: 0 on success, 1 on failure.
    """
    print("\n╔══════════════════════════════════════╗")
    print("║      🚀 Bantz Onboarding Wizard      ║")
    print("╚══════════════════════════════════════╝")

    steps = [
        lambda: _step_env_check(),
        lambda: _step_env_file(non_interactive),
        lambda: _step_google_oauth(non_interactive),
        lambda: _step_llm_backend(non_interactive),
    ]

    for step_fn in steps:
        try:
            ok = step_fn()
            if not ok:
                print("\n  ❌ Setup aborted due to error above.")
                return 1
        except KeyboardInterrupt:
            print("\n\n  Setup cancelled by user.")
            return 1
        except Exception as exc:
            logger.exception("Onboard step failed")
            print(f"\n  ❌ Unexpected error: {exc}")
            return 1

    _step_summary()
    return 0
